service: titan-BE

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1

plugins:
  - serverless-iam-roles-per-function

functions:
  post-upload-pdf:
    handler: src/post-upload-pdf/index.handler
    iamRoleStatementsInherit: true
    iamRoleStatementsName: post-upload-pdf-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::titan-intake-upload-pdf-challenge/*

    events:
      - http:
          path: /upload-pdf
          method: POST
          cors: true

    environment:
      ETHERFAX_API_KEY: arn:aws:secretsmanager:us-east-1:039297709667:secret:etherfax-api-key-pfv8JD

    package:
      include:
        - src/post-upload-pdf/index.js
