service: titan-BE

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1

functions:
  titan:
    handler: src/handler.titanLogic
    timeout: 60 # seconds
    memorySize: 128 # mb
